//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP_323Madanbekov
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrders
    {
        public int OrderID { get; set; }
        public string CustomerName { get; set; }
        public int BrokenPartID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> UsedPartID { get; set; }
        public Nullable<decimal> Revenue { get; set; }
    
        public virtual Parts Parts { get; set; }
        public virtual Parts Parts1 { get; set; }
    }
}
