//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP_323Madanbekov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finance
    {
        public int FinanceID { get; set; }
        public string OperationType { get; set; }
        public decimal Amount { get; set; }
        public decimal BalanceAfterOperation { get; set; }
        public System.DateTime OperationDate { get; set; }
        public string Description { get; set; }
    }
}
