//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP_323Madanbekov
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameState
    {
        public int StateID { get; set; }
        public decimal CurrentBalance { get; set; }
        public int CustomerCounter { get; set; }
        public bool IsGameActive { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
