//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP_323Madanbekov
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrders
    {
        public int OrderID { get; set; }
        public int PartID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int ArrivalCounter { get; set; }
    
        public virtual Parts Parts { get; set; }
    }
}
